name: Build Registry Index

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-index:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Build indexes
      run: |
        node scripts/build-index.js
    
    - name: Commit indexes
      if: github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _index/
        git diff --staged --quiet || git commit -m "Update registry indexes [skip ci]"
        git push