name: DNS Sync on Merge

on:
  push:
    branches:
      - main
    paths:
      - 'modules/**/*.json'

jobs:
  validate-and-sync:
    runs-on: ubuntu-latest
    
    # Only run if the push is to main (not a PR)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Build combined registry
      run: |
        node tools/build-registry.js
        
    - name: Validate modules
      run: |
        node tools/validate.js --skip-content
        
    - name: Sync DNS records
      env:
        DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
        DNSIMPLE_ACCOUNT_ID: ${{ secrets.DNSIMPLE_ACCOUNT_ID }}
      run: |
        node tools/dns-sync.js
        
    - name: Commit build and sync results
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Check for changes to commit
        changes=""
        if [[ -n $(git status -s modules.json) ]]; then
          git add modules.json
          changes="modules.json"
        fi
        
        if [[ -n $(git status -s dns/records.json) ]]; then
          git add dns/records.json
          if [[ -n "$changes" ]]; then
            changes="$changes, dns/records.json"
          else
            changes="dns/records.json"
          fi
        fi
        
        if [[ -n "$changes" ]]; then
          git commit -m "chore: update $changes [skip ci]"
          git push
          echo "✅ Committed updates to: $changes"
        else
          echo "No changes to commit"
        fi
        
    - name: Create sync summary
      if: always()
      run: |
        echo "## DNS Sync Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -f dns/records.json ]; then
          echo "### Updated Records" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat dns/records.json | jq '.records[] | select(.action != "unchanged")' >> $GITHUB_STEP_SUMMARY || echo "No changes"
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        else
          echo "DNS sync did not complete successfully" >> $GITHUB_STEP_SUMMARY
        fi