name: LLM PR Review

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'modules/**/*.json'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  llm-review:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for diff
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install mlld and Claude CLI
      run: |
        npm install -g mlld@1.0.0-rc-3
        npm install -g @anthropic-ai/claude-code
        
    - name: Build combined registry
      run: |
        node tools/build-registry.js
        
    - name: Generate PR review using mlld
      run: |
        # Debug: Check if variables are set
        echo "PR_NUMBER=${{ github.event.number }}"
        echo "ANTHROPIC_API_KEY exists: ${{ secrets.ANTHROPIC_API_KEY != '' }}"
        echo "ANTHROPIC_API_KEY length: ${#ANTHROPIC_API_KEY}"
        
        # First run debug script
        echo "=== Running debug script ==="
        PR_NUMBER="${{ github.event.number }}" \
        REPO_OWNER="${{ github.repository_owner }}" \
        REPO_NAME="${{ github.event.repository.name }}" \
        PR_TITLE="${{ github.event.pull_request.title }}" \
        PR_AUTHOR="${{ github.event.pull_request.user.login }}" \
        ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_API_KEY }}" \
        GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
        mlld --stdout tools/llm-review-debug.mld
        
        echo "=== Running actual review ==="
        # Pass environment variables directly to mlld
        PR_NUMBER="${{ github.event.number }}" \
        REPO_OWNER="${{ github.repository_owner }}" \
        REPO_NAME="${{ github.event.repository.name }}" \
        PR_TITLE="${{ github.event.pull_request.title }}" \
        PR_AUTHOR="${{ github.event.pull_request.user.login }}" \
        ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_API_KEY }}" \
        GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
        mlld --stdout tools/llm-review-claude-cli.mld
        
    - name: Auto-approve if recommended
      if: env.LLM_RECOMMENDATION == 'APPROVE'
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            event: 'APPROVE',
            body: '🤖 **mlld Registry Bot**\n\n✅ **Decision: APPROVED**\n\n' + process.env.LLM_REVIEW_REASONING + '\n\n---\n*I am an automated reviewer powered by Claude AI. I help maintain quality standards for the mlld module registry.*'
          });
          
    - name: Request changes if issues found
      if: env.LLM_RECOMMENDATION == 'REQUEST_CHANGES'
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            event: 'REQUEST_CHANGES',
            body: '🤖 **mlld Registry Bot**\n\n❌ **Decision: CHANGES REQUESTED**\n\n' + process.env.LLM_REVIEW_REASONING + '\n\n---\n*I am an automated reviewer powered by Claude AI. I help maintain quality standards for the mlld module registry.*'
          });
          
    - name: Comment with review
      if: env.LLM_RECOMMENDATION == 'COMMENT'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: '🤖 **mlld Registry Bot**\n\n💬 **Decision: COMMENT**\n\n' + process.env.LLM_REVIEW_REASONING + '\n\n---\n*I am an automated reviewer powered by Claude AI. I help maintain quality standards for the mlld module registry.*'
          });