name: LLM PR Review

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'modules/**/*.json'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  llm-review:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for diff
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install mlld
      run: |
        npm install -g mlld@1.0.0-rc-3
        
    - name: Build combined registry
      run: |
        node tools/build-registry.js
        
    - name: Generate PR review using mlld
      run: |
        # Pass environment variables directly to mlld
        PR_NUMBER="${{ github.event.number }}" \
        REPO_OWNER="${{ github.repository_owner }}" \
        REPO_NAME="${{ github.event.repository.name }}" \
        PR_TITLE="${{ github.event.pull_request.title }}" \
        PR_AUTHOR="${{ github.event.pull_request.user.login }}" \
        ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_API_KEY }}" \
        GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
        mlld tools/llm-review-final.mld
        
    - name: Auto-approve if recommended
      if: env.LLM_RECOMMENDATION == 'APPROVE'
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            event: 'APPROVE',
            body: '🤖 **Auto-approved by LLM Reviewer**\n\n' + process.env.LLM_REVIEW_REASONING
          });
          
    - name: Request changes if issues found
      if: env.LLM_RECOMMENDATION == 'REQUEST_CHANGES'
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            event: 'REQUEST_CHANGES',
            body: '🤖 **Issues found by LLM Reviewer**\n\n' + process.env.LLM_REVIEW_REASONING
          });
          
    - name: Comment with review
      if: env.LLM_RECOMMENDATION == 'COMMENT'
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: '🤖 **LLM Reviewer Notes**\n\n' + process.env.LLM_REVIEW_REASONING + '\n\n*Requires human review.*'
          });