name: Validation Status

on:
  pull_request:
    paths:
      - 'modules.json'
      - 'modules/**/*.json'

permissions:
  contents: read
  statuses: write
  checks: write

jobs:
  validate-status:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Build combined registry
      run: |
        node tools/build-registry.js
        
    - name: Validate modules
      id: validation
      run: |
        if node tools/validate.js --save-report; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "Valid registry - all modules passed validation" >> $GITHUB_STEP_SUMMARY
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "Registry validation failed - see report for details" >> $GITHUB_STEP_SUMMARY
        fi
        
    - name: Parse validation report
      if: always()
      run: |
        if [ -f validation-report.json ]; then
          echo "## Validation Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          node -e "
            const report = require('./validation-report.json');
            console.log('- Total modules:', report.modules);
            console.log('- Valid:', report.valid);
            console.log('- Invalid:', report.invalid);
            console.log('- Total errors:', report.totalErrors);
            
            if (report.invalid > 0) {
              console.log('\\n### Errors by module:\\n');
              for (const [moduleId, result] of Object.entries(report.results)) {
                if (!result.valid) {
                  console.log('**' + moduleId + '**:');
                  result.errors.forEach(err => console.log('- ' + err));
                  console.log('');
                }
              }
            }
          " >> $GITHUB_STEP_SUMMARY
        fi
        
    - name: Set commit status
      if: always()
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const status = '${{ steps.validation.outputs.status }}';
          const state = status === 'success' ? 'success' : 'failure';
          const description = status === 'success' 
            ? 'All modules are valid' 
            : 'Module validation failed - check summary';
          
          try {
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: state,
              target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              description: description,
              context: 'mlld-registry/validation'
            });
          } catch (error) {
            console.log('Failed to set commit status:', error.message);
          }